import { Card, TypeCard } from "./types";



export const cards: Array<Card> = [
  { id: 1, rank: 6, type: TypeCard.bubi, img: 'cards/1b.bmp' },
  { id: 2, rank: 6, type: TypeCard.chervi, img: 'cards/1c.bmp' },
  { id: 3, rank: 6, type: TypeCard.kresti, img: 'cards/1k.bmp' },
  { id: 4, rank: 6, type: TypeCard.piki, img: 'cards/1p.bmp' },
  { id: 5, rank: 7, type: TypeCard.bubi, img: 'cards/2b.bmp' },
  { id: 6, rank: 7, type: TypeCard.chervi, img: 'cards/2c.bmp' },
  { id: 7, rank: 7, type: TypeCard.kresti, img: 'cards/2k.bmp' },
  { id: 8, rank: 7, type: TypeCard.piki, img: 'cards/2p.bmp' },
  { id: 9, rank: 8, type: TypeCard.bubi, img: 'cards/3b.bmp' },
  { id: 10, rank: 8, type: TypeCard.chervi, img: 'cards/3c.bmp' },
  { id: 11, rank: 8, type: TypeCard.kresti, img: 'cards/3k.bmp' },
  { id: 12, rank: 8, type: TypeCard.piki, img: 'cards/3p.bmp' },
  { id: 13, rank: 9, type: TypeCard.bubi, img: 'cards/4b.bmp' },
  { id: 14, rank: 9, type: TypeCard.chervi, img: 'cards/4c.bmp' },
  { id: 15, rank: 9, type: TypeCard.kresti, img: 'cards/4k.bmp' },
  { id: 16, rank: 9, type: TypeCard.piki, img: 'cards/4p.bmp' },
  { id: 17, rank: 10, type: TypeCard.bubi, img: 'cards/5b.bmp' },
  { id: 18, rank: 10, type: TypeCard.chervi, img: 'cards/5c.bmp' },
  { id: 19, rank: 10, type: TypeCard.kresti, img: 'cards/5k.bmp' },
  { id: 20, rank: 10, type: TypeCard.piki, img: 'cards/5p.bmp' },
  { id: 21, rank: 11, type: TypeCard.bubi, img: 'cards/6b.bmp' },
  { id: 22, rank: 11, type: TypeCard.chervi, img: 'cards/6c.bmp' },
  { id: 23, rank: 11, type: TypeCard.kresti, img: 'cards/6k.bmp' },
  { id: 24, rank: 11, type: TypeCard.piki, img: 'cards/6p.bmp' },
  { id: 25, rank: 12, type: TypeCard.bubi, img: 'cards/7b.bmp' },
  { id: 26, rank: 12, type: TypeCard.chervi, img: 'cards/7c.bmp' },
  { id: 27, rank: 12, type: TypeCard.kresti, img: 'cards/7k.bmp' },
  { id: 28, rank: 12, type: TypeCard.piki, img: 'cards/7p.bmp' },
  { id: 29, rank: 13, type: TypeCard.bubi, img: 'cards/8b.bmp' },
  { id: 30, rank: 13, type: TypeCard.chervi, img: 'cards/8c.bmp' },
  { id: 31, rank: 13, type: TypeCard.kresti, img: 'cards/8k.bmp' },
  { id: 32, rank: 13, type: TypeCard.piki, img: 'cards/8p.bmp' },
  { id: 33, rank: 14, type: TypeCard.bubi, img: 'cards/9b.bmp' },
  { id: 34, rank: 14, type: TypeCard.chervi, img: 'cards/9c.bmp' },
  { id: 35, rank: 14, type: TypeCard.kresti, img: 'cards/9k.bmp' },
  { id: 36, rank: 14, type: TypeCard.piki, img: 'cards/9p.bmp' },
]